CREATE TABLE [dbo].[Clients]
(
	[Id] INT NOT NULL PRIMARY KEY,
	[Name] NVARCHAR(MAX) NOT NULL,
	[Sex] NVARCHAR(MAX) NOT NULL,
	[PhoneNum] NVARCHAR(MAX) NOT NULL,
	[Passport] NVARCHAR(MAX) NOT NULL,
	[BirthDate] NVARCHAR(MAX) NOT NULL,
	[Residence] NVARCHAR(MAX) NOT NULL,
	[Email] NVARCHAR(MAX) NOT NULL
)
