CREATE TABLE [dbo].[Cars]
(
	[Id] INT NOT NULL PRIMARY KEY,
	[Mark] NVARCHAR(MAX) NOT NULL,
	[Model] NVARCHAR(MAX) NOT NULL,
	[ReleaseDate] DATE NOT NULL,
	[Producer] NVARCHAR(MAX) NOT NULL,
	[VINCode] NVARCHAR(MAX) NOT NULL,
	[PTSNum] NVARCHAR(MAX) NOT NULL,
	[BodyType] NVARCHAR(MAX) NOT NULL,
	[FuelType] NVARCHAR(MAX) NOT NULL,
	[Transmission] NVARCHAR(MAX) NOT NULL,
	[EngineModel] NVARCHAR(MAX) NOT NULL,
	[EnginePower] NVARCHAR(MAX) NOT NULL,
	[EngineCapacity] NVARCHAR(MAX) NOT NULL,
	[Weight] NVARCHAR(MAX) NOT NULL,
	[Country] NVARCHAR(MAX) NOT NULL,
	[Price] MONEY NOT NULL
)
